package com.zorro.kotlin.samples.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zorro.kotlin.samples.db.entity.LocalFile;

import com.zorro.kotlin.samples.db.LocalFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localFileDaoConfig;

    private final LocalFileDao localFileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localFileDaoConfig = daoConfigMap.get(LocalFileDao.class).clone();
        localFileDaoConfig.initIdentityScope(type);

        localFileDao = new LocalFileDao(localFileDaoConfig, this);

        registerDao(LocalFile.class, localFileDao);
    }
    
    public void clear() {
        localFileDaoConfig.clearIdentityScope();
    }

    public LocalFileDao getLocalFileDao() {
        return localFileDao;
    }

}
